'use strict';
const assert = require('assert');
const Engine = require('../../wordpress/catalyst-canvas-demo/assets/catalyst-canvas-engine.js');
const source = require('../../fixtures/canvas_contract_1_4.input.json');
const contract = Engine.buildContract(source, 'wordpress');
assert.strictEqual(contract.schema_version, 'catalyst-canvas/1.4');
assert.strictEqual(contract.decision_options.length, 3);
assert.strictEqual(contract.sensitivity_views[0].name, 'Baseline weights');
const baseline = contract.sensitivity_views[0].rankings.map(item => item.option_id);
const constrained = contract.sensitivity_views.find(item => item.name === 'Delivery constraint').rankings.map(item => item.option_id);
assert.notDeepStrictEqual(baseline, constrained);
const rawBefore = contract.decision_options.map(option => option.criterion_scores.map(score => score.raw_value));
const rebuilt = Engine.buildContract(contract, 'wordpress');
const rawAfter = rebuilt.decision_options.map(option => option.criterion_scores.map(score => score.raw_value));
assert.deepStrictEqual(rawBefore, rawAfter);
const decisionPackage = Engine.buildDecisionHandoffPackage(contract, 'decision_studio');
assert.strictEqual(decisionPackage.handoff_contract, 'catalyst-canvas-decision-handoff/1.0');
assert.ok(decisionPackage.decision_context.alternatives.length);
assert.ok(decisionPackage.decision_context.criteria.length);
assert.ok(decisionPackage.decision_context.assumptions.length);
assert.ok(decisionPackage.decision_context.evidence.length);
assert.ok(decisionPackage.decision_context.unresolved_questions.length);
const workbenchPackage = Engine.buildDecisionHandoffPackage(contract, 'workbench');
assert.ok(workbenchPackage.technical_validation.inputs.length);
console.log('PASS: WordPress prioritization and decision-readiness engine.');
