'use strict';
const assert = require('assert');
const Engine = require('../../wordpress/catalyst-canvas-demo/assets/catalyst-canvas-engine.js');
const source = require('../../fixtures/canvas_contract_2_0.input.json');
const expected = require('../../fixtures/canvas_contract_2_0.expected.json');
const contract = Engine.buildContract(source, 'python');
assert.deepStrictEqual(contract, expected);
assert.strictEqual(contract.schema_version, 'catalyst-canvas/2.0');
assert.strictEqual(contract.platform_summary.connection_count, 3);
assert.strictEqual(contract.platform_summary.readiness, 'connected_but_not_ready');
const exchange = Engine.buildExchangePackage(contract, 'decision_studio', 'decision', 'profile-institutional-v1');
assert.strictEqual(exchange.exchange_contract, 'catalyst-canvas-exchange/2.0');
assert.strictEqual(exchange.target.product, 'decision_studio');
assert.strictEqual(exchange.payload_type, 'decision');
const capabilities = Engine.capabilityManifest(contract);
assert.strictEqual(capabilities.canvas_contract, 'catalyst-canvas/2.0');
assert.ok(capabilities.capabilities.includes('signed_exchange'));
const migrated = Engine.migratePayload(require('../../fixtures/canvas_contract_1_6.expected.json'));
assert.strictEqual(migrated.contract.schema_version, 'catalyst-canvas/2.0');
assert.strictEqual(migrated.migrated_from, 'catalyst-canvas/1.6');
console.log('PASS: connected platform browser contract.');
